# Generated by Django 5.2.6 on 2025-09-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('paused', 'Paused')], default='active', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('hostage_timer', models.FloatField(default=40.0)),
                ('ultron_position_x', models.IntegerField(default=0)),
                ('ultron_position_y', models.IntegerField(default=7)),
                ('ultron_target_x', models.IntegerField(default=14)),
                ('ultron_target_y', models.IntegerField(default=7)),
                ('shields_placed', models.TextField(default='[]')),
                ('game_start_time', models.DateTimeField(auto_now_add=True)),
                ('game_end_time', models.DateTimeField(blank=True, null=True)),
                ('time_survived', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shield_placed', 'Shield Placed'), ('ultron_moved', 'Ultron Moved'), ('ultron_paused', 'Ultron Paused'), ('timer_increased', 'Timer Increased'), ('game_won', 'Game Won'), ('game_lost', 'Game Lost')], max_length=20)),
                ('data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_score', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('total_time_survived', models.FloatField(default=0.0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-highest_score', '-games_won'],
            },
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_type', models.CharField(choices=[('blue', 'Full Block Shield'), ('yellow', 'Delay Shield'), ('red', 'Pause Shield')], max_length=10)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shields', to='game.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'position_x', 'position_y')},
            },
        ),
    ]
