# Generated by Django 5.2.6 on 2025-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='durability',
            field=models.IntegerField(default=1),
        ),
    ]
