# Generated by Django 5.2.6 on 2025-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_shield_durability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_move_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ultron_paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('shield_placed', 'Shield Placed'), ('shield_destroyed', 'Shield Destroyed'), ('ultron_moved', 'Ultron Moved'), ('ultron_paused', 'Ultron Paused'), ('timer_reduced', 'Timer Reduced'), ('timer_increased', 'Timer Increased'), ('game_won', 'Game Won'), ('game_lost', 'Game Lost')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shield',
            name='shield_type',
            field=models.CharField(choices=[('blue', 'Full Block Shield'), ('yellow', 'Timer Reduction Shield'), ('red', 'Pause Shield')], max_length=10),
        ),
    ]
