# Generated by Django 5.2.6 on 2025-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession_last_move_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='last_move_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
