# Generated by Django 5.2.6 on 2025-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamesession_last_move_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='ultron_position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='ultron_target_x',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='ultron_target_y',
            field=models.IntegerField(default=13),
        ),
    ]
