# Generated by Django 5.2.6 on 2025-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamesession_ultron_position_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='last_timer_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
